# Generated by Django 6.0.2 on 2026-02-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('es_beneficiario', models.BooleanField(default=False)),
                ('extens', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
