# Generated by Django 6.0.2 on 2026-02-08 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clientes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Asunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('tipo', models.CharField(choices=[('reunion', 'Reunión'), ('taller', 'Taller'), ('entrega_semillas', 'Entrega de Semillas'), ('mercado', 'Mercado Campesino'), ('gira', 'Gira/Visita Técnica'), ('charla', 'Charla/Capacitación'), ('otro', 'Otro')], default='reunion', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('total_instancias', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_asistentes_registrados', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['-fecha_postulacion']},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['rut'], name='app_cliente_rut_909a50_idx'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['sector'], name='app_cliente_sector_085178_idx'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['es_beneficiario'], name='app_cliente_es_bene_4994d2_idx'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app.clientes'),
        ),
        migrations.AlterUniqueTogether(
            name='asunto',
            unique_together={('nombre',)},
        ),
        migrations.AddField(
            model_name='registroasunto',
            name='asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app.asunto'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='registro_asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app.registroasunto'),
        ),
        migrations.AddIndex(
            model_name='registroasunto',
            index=models.Index(fields=['asunto', 'fecha'], name='app_registr_asunto__43556b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('cliente', 'registro_asunto')},
        ),
    ]
