# Generated by Django 6.0.2 on 2026-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_asistencia_asunto_registroasunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asunto',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='asuntos_asociados', to='app.clientes'),
        ),
    ]
