# Generated by Django 4.2.27 on 2026-02-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_migrate_capacitacion_to_charla'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('sin_estudios', 'Sin Estudios'), ('basica_incompleta', 'Básica Incompleta'), ('basica_completa', 'Básica Completa'), ('media_incompleta', 'Media Incompleta'), ('media_completa', 'Media Completa'), ('tecnica', 'Técnica'), ('superior', 'Superior')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('soltera', 'Soltera'), ('divorciado', 'Divorciado/a'), ('separado', 'Separado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión Libre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='ingresos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_tenencia',
            field=models.CharField(blank=True, choices=[('propietario', 'Propietario'), ('arrendatario', 'Arrendatario'), ('prestado', 'Prestado'), ('ocupante', 'Ocupante')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='vivienda_saneada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posee_registro', models.BooleanField(blank=True, help_text='¿Posee Registro Social de Hogares?', null=True)),
                ('puntaje', models.CharField(blank=True, help_text='Puntaje del registro', max_length=50, null=True)),
                ('actualizado', models.BooleanField(blank=True, help_text='¿Está actualizado?', null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_social', to='app.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='RedConocida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redes_conoce', models.TextField(blank=True, help_text='Redes que conoce (JJVV, Clubes, etc)', null=True)),
                ('redes_participa', models.TextField(blank=True, help_text='Redes en que participa', null=True)),
                ('redes_apoyo', models.TextField(blank=True, help_text='Redes de apoyo disponibles', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redes_conocidas', to='app.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.TextField(blank=True, help_text='Enfermedades diagnosticadas', null=True)),
                ('toma_medicamentos', models.BooleanField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, help_text='Lista de medicamentos', null=True)),
                ('controles_medicos', models.TextField(blank=True, help_text='Tipo de controles (ronda médica, sabat, etc)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_salud', to='app.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('luz', models.BooleanField(blank=True, help_text='¿Tiene acceso a luz eléctrica?', null=True)),
                ('agua', models.BooleanField(blank=True, help_text='¿Tiene acceso a agua potable?', null=True)),
                ('rol', models.CharField(blank=True, help_text='Rol en el registro', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona_principal', models.OneToOneField(help_text='Persona responsable del hogar', on_delete=django.db.models.deletion.CASCADE, related_name='hogar', to='app.clientes')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('hijo', 'Hijo/a'), ('padre', 'Padre'), ('madre', 'Madre'), ('abuelo', 'Abuelo/a'), ('hermano', 'Hermano/a'), ('otros', 'Otros')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('escolaridad', models.CharField(blank=True, choices=[('sin_estudios', 'Sin Estudios'), ('basica_incompleta', 'Básica Incompleta'), ('basica_completa', 'Básica Completa'), ('media_incompleta', 'Media Incompleta'), ('media_completa', 'Media Completa'), ('tecnica', 'Técnica'), ('superior', 'Superior')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carga_familiar', to='app.hogar')),
            ],
            options={
                'ordering': ['hogar', 'parentesco'],
            },
        ),
        migrations.CreateModel(
            name='AnotacionesHogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesidades', models.TextField(blank=True, help_text='Necesidades identificadas', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales', null=True)),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones propuestas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hogar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='app.hogar')),
            ],
        ),
    ]
