# Generated by Django 4.2.27 on 2026-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_clientes_edad_clientes_escolaridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
